# Generated by Django 3.2.16 on 2023-02-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_signin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
