# Generated by Django 3.2.16 on 2023-02-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_signin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
