# Generated by Django 4.1.6 on 2023-02-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_alter_signin_phone_alter_signin_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='address',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='signin',
            name='password',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
